GET http://localhost:3000/users HTTP/1.1
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImE4YmZhNzU2NDk4ZmRjNTZlNmVmODQ4YWY5NTI5ZThiZWZkZDM3NDUiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vY29udHJhY3RvcnMtZjFkNTEiLCJhdWQiOiJjb250cmFjdG9ycy1mMWQ1MSIsImF1dGhfdGltZSI6MTY2MDI2MjA2MCwidXNlcl9pZCI6ImJvNnVyRDRiQjVnTk5MYkpCYUY1UGFsM2pkYzIiLCJzdWIiOiJibzZ1ckQ0YkI1Z05OTGJKQmFGNVBhbDNqZGMyIiwiaWF0IjoxNjYxMzg0MDM5LCJleHAiOjE2NjEzODc2MzksImVtYWlsIjoiaW5mb0Btb3Fhd2xhdHkuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbImluZm9AbW9xYXdsYXR5LmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.JylphViSuqOtUTIFcnrowqAflnIivaXOOdzp3tLAjiLDhOXelMbxOAXDFzWuJtkjY49AvF2GHl84Iz8RSsUxAudhAfNREbZTnxVSEKFg02FpYm495tnGM6d4d7FYzIt6FbpXwo3o9BTyy_KPng9nmfYo6CbGG_StolHF520Bjt5nlbTQ7cjqbZHpG5rZQz3mUOPB3vNYQ-KrGC8suWCmcYGnxMA2U5UVaq8-y6vpIqIZrklsp_ClPJKLd5lPZamvvWQt8_zmbh01AeBWrgbgB2gZ6yR7Jdwh7Cu4TF0liS8I4YsjYQuEDS9dpLK0mp8CovkMytPgmCrJHSMKYOwLMg
