steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build'
    args: ['build', '--no-cache' ,'-t', '${_IMAGE_NAME}', '.','-f','Dockerfile']
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push'
    args: ['push', '${_IMAGE_NAME}']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    id: 'Deploy'
    args: ['gcloud', 'run', 'services', 'update', 'knot', '--platform=managed','--image', '${_IMAGE_NAME}','--labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=${COMMIT_SHA},gcb-build-id=${BUILD_ID},gcb-trigger-name=${TRIGGER_NAME}','--region=us-central1', '--quiet']
timeout: 1800s
substitutions:
  _IMAGE_NAME: 'gcr.io/${PROJECT_ID}/${REPO_NAME}/knot:${REVISION_ID}'
options:
  dynamic_substitutions: true
#  machineType: 'E2_HIGHCPU_8'